name: CICD pipeline
on: [push]
jobs:
    python:
          runs-on: ubuntu-latest
          steps:
              - name: pulling python script
                uses: actions/checkout@v2
              - name: running python script
                run: python hello.py
    build: 
          runs-on: ubuntu-18.04
          needs: [python]

          steps:
              - name: building artifact
                uses: actions/checkout@v2
              - uses: actions/upload-artifact@v2
  
                with:
                    name: hello
                    path: .
